### PR TITLE
Added option that allows to specify path

### PR DESCRIPTION
**Pull request by rcasula**
### Description of the pull request

This PR Adds support for specifying a custom path in the options.

### CODE REVIEW

**Comment by robcas3** [comment]
Any update on this?

**Comment by robcas3** [comment]
Done.

**Comment by robcas3** [comment]
Any update on this?

**Comment by rcasula** [comment]
updates?

**Comment by danielrbrowne** [comment]
@rcasula Can I ask what use case are you looking to address with this change?

**Comment by rcasula** [comment]
We use a custom install of PusherServer under a custom path, behind a proxy. 
We simply want to use the same domain for websockets and other HTTP traffic and we don't need to use http tunneling.

Also this is originally implemented by the javascript library.

For reference, this modification was merged also in the php library:
[https://github.com/pusher/pusher-http-php/pull/227](#227)

**Review by devdreamsolution — APPROVED** [review]

**Review by devdreamsolution — APPROVED** [review]

**Comment by danielrbrowne** [comment]
@rcasula Apologies for the large delay in replying to you. If you update this PR merging the latest version of `master` from our upstream branch to resolve the merge conflicts with `Package.swift` then I will merge this PR ASAP

**Comment by rcasula** [comment]
@danielrbrowne Done.

**Pull request merged**
