### PR TITLE
Changed a few references to NSURLRequest/NSMutableURLRequest to URLRequest

### PR DESCRIPTION
**Pull request by Noobish1**

### CODE REVIEW

**Comment by hamchapman** [comment]
I think I had this originally when working on the Swift 3 branch but then I believe I needed to keep `NSMutableRequest` for the Obj-C compat. I'll have a check though.

Do you need the type to be `URLRequest` for your use case?

**Comment by Noobish1** [comment]
We do yea

**Comment by hamchapman** [comment]
Just been testing this locally and it does in fact seem to work fine with the Obj-C stuff, so this will likely go into a 4.0.1 release 👍

**Comment by hamchapman** [comment]
Closed in favour of #107

**Pull request closed without merging**
