### PR TITLE
[WIP] 1.0.0 release

### PR DESCRIPTION
**Pull request by hamchapman**
- [x] Split up PusherSwift into multiple files
- [x] Split up tests into multiple files
- [x] Bring CryptoSwift, Starscream and Reachability dependencies inside the library
- [x] Add documentation to code
- [x] Add `onMemberAdded` and `onMemberRemoved` properties to presence channel
- [x] Add `findMember` and `me` functions to presence channel
- [x] Change connection change delegate based on comments in #50 
- [x] Add ability to have logging for all messages, as in #45 
- [x] Investigate handling client errors better #52
- [x] Clean up cocoapods-related code
- [x] Check carthage still working
- [x] Final checks

### CODE REVIEW

**Comment by ay8s** [comment]
Amazing work @hamchapman. Was just wondering how I could access these. 👍

**Comment by hamchapman** [comment]
@ay8s I've fixed the `onMemberAdded` related code and added `findMember` and `me` functions to the  presence channel class. Let me know if it's now working as you'd expect!

**Comment by ay8s** [comment]
Perfect @hamchapman. Will give it a whirl tonight and let you know if I spot anything. 👍

**Comment by ay8s** [comment]
Looking good from my end @hamchapman. I wonder if it's possible to make PresenceChannelMember hashable at all? Planning to store PresenceChannelMember's against views/names etc which adding would make super easy!

**Comment by hamchapman** [comment]
Great - would you be happy to create a PR for making `PresenceChannelMember` hashable? It sounds like a good idea but I don't really have the time to do it at the moment :)

**Comment by hamchapman** [comment]
Or is it maybe easier to just make the `members` array into a dictionary where the keys are `user_ids`?

**Comment by ay8s** [comment]
I think I might be able to simply use the user_id itself rather than need it to be hashable. I'm not running a server so don't quite have any other information in there to use. :)

**Pull request merged**
