### PR TITLE
Swift 3 and single target

### PR DESCRIPTION
**Pull request by hamchapman**
* Updates to work with Swift 3
* Rewrite all tests using XCTest
* Remove all need for Podfile / Cartfile
* Combine different builds into single target
* Merges in native notification code into main branch
* Adds subscription success / error handlers
* Makes `requestFor` in `AuthRequestBuilderProtocol` able to fail
* Renames `PresencePusherChannel` -> `PusherPresenceChannel`
* Rename `internal` authMethod enum case to `inline`
* Added Obj-C compatibility 
* Added iOS Obj-C example app
* Add `subscribeToPresenceChannel` method

### CODE REVIEW

**Comment by rabc** [comment]
Hi!

Do you have any idea when the migration to Swift 3 will be finished?

**Comment by hamchapman** [comment]
The Swift 3 migration itself is done. There's just a bit of tidy up to do in the docs / examples and then I think it's good to go for a 3.0.0 release. Feel free to try stuff out with this branch before I cut the release though. It all compiles and the tests pass etc.

**Comment by rabc** [comment]
Awesome! Thanks! You will merge it and create a new version for Cocoapods today?

**Comment by hamchapman** [comment]
Hopefully yes - need to do a few more bits and pieces first

**Comment by hamchapman** [comment]
I didn't quite have time to release it yesterday but am going to do it this morning.

**Pull request merged**
