### PR TITLE
Reachability fix

### PR DESCRIPTION
**Pull request by QuimeraKoke**
Hi,
I fix the issue #115 as I explained in the thread.

* added async at whenReachable and whenReachable block
* let self retained in whenReachable and whenReachable block

### CODE REVIEW

**Comment by theMeatloaf** [comment]
I'm using this PR version in my production app and it has somehow caused my connections to increase...I believe it has caused a memory leak which is duplicating pusher objects and thus increasing the connection count.

**Comment by hamchapman** [comment]
Thanks for the info @theMeatloaf. I think that's what I would have expected seeing as the `[weak self]` is removed by this PR. 

Can I ask why you were testing this PR? Were you also seeing the starscream crash?

**Comment by theMeatloaf** [comment]
Yes I was seeing the starscream crash in high volumes, essentially making the lib unusable.  I will look into a better solution, but i'm not fully versed on the cause so we'll see what I can come up wtih

**Comment by theMeatloaf** [comment]
isnt the solution to just keep the `[weak self]` isntead of `unowned` ?

**Comment by theMeatloaf** [comment]
Yeah looking at the basic area of the crash, it appears that a `weak` reference to self is what is needed here.  @hamchapman If you think the current version of this file in the repo will fix the issues i'd be happy to try it out.

**Comment by hamchapman** [comment]
Agreed that having a `weak` reference to `self` in the closure is what is needed. And that's what it currently has on master. I'm still just unsure as to how the rest of the changes in this PR would fix any kind of Staracream queue crash

**Comment by theMeatloaf** [comment]
I'm not sure i fully understand the Starscream crash but it sounds like the memory leak generated by this PR had the side effect that it fixed it since the referenced objects that previously were getting deallocated have leaked and are no longer crashing...

The team at pusher keeps contacting our team about hitting our connection limit so i think i'm going to try and see if the current master branch fixes my issues... i'll let you know @hamchapman

**Comment by hamchapman** [comment]
@theMeatloaf did you find that master fixed your issues?

**Comment by theMeatloaf** [comment]
Yes it does appear to have fixed my issues.  I occasionally do see the "Your pusher instance has been deallocated" message in the log but it still continues to respond to messages

**Comment by hamchapman** [comment]
Thanks for letting me know. I'm going to close this for now as I don't think it's the right way to fix any potential problems with that bit of the codebase.

**Pull request closed without merging**
