### PR TITLE
Package.swift: adds dynamic library

### PR DESCRIPTION
**Pull request by AndrewSB**
### Description of the pull request

...

#### Why is the change necessary?

...

### CODE REVIEW

**Comment by danielrbrowne** [comment]
@AndrewSB Can you add some details to the description regarding the purpose of this PR and the issues it resolves for you and/or your team?

**Comment by AndrewSB** [comment]
hey! this is a workaround for the issue described here https://forums.swift.org/t/swift-packages-in-multiple-targets-results-in-this-will-result-in-duplication-of-library-code-errors/34892

**Comment by danielrbrowne** [comment]
@AndrewSB Our CI pipeline is currently failing due to an issue I've reported to Carthage... In the meantime, I'm curious if you've tried the Xcode 12.5 beta - discussion in that link you posted suggests there may be a fix for this issue that doesn't require a workaround in `Package.swift`.

**Comment by AndrewSB** [comment]
I actually just downloaded it to try! I'll report back to see if I can use the non-patched pusher once I get around to it

**Comment by danielrbrowne** [comment]
@AndrewSB Apologies for the delay in follow-up with this. It seems the CI problems have been resolved now, so that's good! However, I was wondering if you had any success at your end when using Xcode 12.5. I.e. were you able to build using the latest, unmodified v9.2.2 release of our SDK without an issue?

**Comment by AndrewSB** [comment]
Xcode 12.5 doesn't require this, looks like it works as is!

**Pull request closed without merging**
