### PR TITLE
Update CryptoSwift to 1.1.3 and Reachability.swift to 4.3.1 to quiet build warnings

### PR DESCRIPTION
**Pull request by marcetcheverry**
### Description of the pull request
Update `CryptoSwift` to `1.1.3` and `Reachability.swift` to `4.3.1` to quiet build warnings.

#### Why is the change necessary?
Xcode 11.2.1 show several build warnings with these third party libraries.

See https://github.com/pusher/pusher-websocket-swift/issues/238

While `Reachability.swift` `4.3.1` is not the latest released version, it is the most recent one that builds without further changes to the codebase.

Let me know if I need to make any adjustments to the `CHANGELOG` or the `Carthage` and `SwiftPM` files, I tried to keep changes to a minimum.

### CODE REVIEW

**Comment by marcetcheverry** [comment]
Note, I've only tested this by updating my Podfile reference and it works fine. Please check out the Travis build errors for CryptoSwift.

https://travis-ci.org/pusher/pusher-websocket-swift/builds/609024149?utm_medium=notification&utm_source=github_status

**Comment by JonathanDowning** [comment]
This PR https://github.com/pusher/pusher-websocket-swift/pull/237 potentially supersedes this PR by also adding Swift 5 compatibility. Just waiting for review.

**Comment by marcknock** [comment]
This removes CryptoSwift to keep up to date with master

**Comment by TomKemp** [comment]
Hi @marcetcheverry. Thank you very much for the PR. We've updated the Reachability to a more recent version since you made this PR so I'm going to close it. Sorry that it wasn't merged sooner.

**Pull request closed without merging**
