### PR TITLE
Swift 3.2

### PR DESCRIPTION
**Pull request by hamchapman**
### Description of the pull request

Updates for Swift 3.2.

#### Why is the change necessary?

Small amount of changes required for generic constraints. 

Thanks to @BrendanBuono (this PR will replace #144)

----

CC @pusher/mobile

### CODE REVIEW

**Comment by hamchapman** [comment]
The branch name is `swift-3.2` so you should be able to use that for now if you're using Cocoapods (or some other method that isn't Carthage). 

I'll create a new tag, probably `5.0.0-pre`, for anyone who's using Carthage and wants to be able to more easily reference this.

**Comment by kielgillard** [comment]
Is the intention to merge this branch into `master` or should we use this new branch indefinitely?

I'm all for merging into master and releasing a new version.

**Comment by hamchapman** [comment]
Eventually this will be merged into master, likely when Xcode 9 is released as the current Xcode.

For the time being work for Swift 3.2 (and Swift 4.0, separately) will continue in separate branches: `swift-3.2` (and `swift-4`).

**Comment by kielgillard** [comment]
Hi, me again. I'm noticing the branch is behind `master`. Is there some reason these changes can't be merged into `master`, guarding source breaking changes with version checks like `#if swift(>=3.2)`?

**Comment by kielgillard** [comment]
Hi, me again. I'm noticing the branch is behind `master`. Is there some reason these changes can't be merged into `master`, guarding source breaking changes with version checks like `#if swift(>=3.2)`?

**Comment by dmorrow** [comment]
Now that XCode 9 GM has been released, can this be merged?

**Comment by hamchapman** [comment]
Yep - I'll merge this tomorrow 👍

**Comment by hamchapman** [comment]
I think I'm going to merge this and release it as 5.0.0. 

Then #149 (Swift 4 branch) can be merged and released as 5.0.1.

**Comment by dmorrow** [comment]
@hamchapman can you also bump the podspec to 5.0.0 and add a tag?

**Comment by hamchapman** [comment]
5.0.0 has been released. Just going to do 5.0.1 now for the Swift 4 branch

**Comment by karthisiva** [comment]
I am just updated xcode version 8 to 9 and project not able to run and showing some error in pusher directory class file. What i have to update and what should i do to install version 5.0.0 through pod file?

**Comment by hamchapman** [comment]
Opening master in the latest Xcode (9) works fine for me in terms of the framework and the example app both building successfully. 

What error are you seeing? A screenshot would be great.

**Comment by karthisiva** [comment]
Currently my pod file contains like below : 

# Uncomment this line to define a global platform for your project
 platform :ios, ’10.0’

target 'DailythanthiRevamp' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'PusherSwift'
# Pods for DailythanthiRevamp

  target 'DailythanthiRevampTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DailythanthiRevampUITests' do
    inherit! :search_paths
    # Pods for testing
  end
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
end


The following file having issue: **CryptoSwiftHMACModule.swift**
screen shot 2017-09-21 at 5 46 43 pm

**Comment by hamchapman** [comment]
I think it will be this part in your `Podfile` that is causing the problem:

```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
```

Try removing that entirely to see if the problem remains.

If not, try changing this line: 

`config.build_settings['SWIFT_VERSION'] = '3.0'` 

to 

`config.build_settings['SWIFT_VERSION'] = '3.2'`

**Comment by karthisiva** [comment]
I removed everything and 3.2 as you said but not working still issues coming.
I have created new sample that also showing same.I will send you mail sample project.
kindly look into this, Is there any problem with pod version from my side? i am currently having 1.2.1
version.Thanks for reply.

**Comment by hamchapman** [comment]
Thanks for the sample project - very helpful!

In the sample you sent you're actually getting 4.2.0 being installed.

To fix this, and get 5.0.0 installed, try running the following:

```
pod cache clean
pod repo update PusherSwift
pod install
```

**Comment by karthisiva** [comment]
I am not able to run second command getting fatal error like below

fatal: Cannot change to '/Users/mobileapps/.cocoapods/repos/PusherSwift': No such file or directory
[!] The `PusherSwift` repo is not a git repo.

**Comment by hamchapman** [comment]
Ah I got the commands slightly wrong, my bad.

You'll want to run:

```
pod cache clean PusherSwift
pod repo update
pod install
```

Let me know if _that_ works!

**Comment by karthisiva** [comment]
No luck!!! still showing error.I will create new one and check it.

**Comment by hamchapman** [comment]
You could try changing the `PusherSwift` line in your `Podfile` to this:

`pod 'PusherSwift', '5.0.0'`

**Comment by karthisiva** [comment]
Not working..

Analyzing dependencies
Downloading dependencies
Installing PusherSwift (5.0.0)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.

Version 5.0.0 installed, still error coming

**Comment by hamchapman** [comment]
Same errors? Could you provide another screenshot? I don't have the errors locally when I use 5.0.0.

**Comment by karthisiva** [comment]
As i can see installing version 5.0.0 after that i ran command+B to build always failed

screen shot 2017-09-22 at 4 04 37 pm

**Comment by karthisiva** [comment]
any help???

**Comment by hamchapman** [comment]
What does your `Podfile` look like now?

Mine looks like this:

```ruby
target 'PusherSam' do
  use_frameworks!
  pod 'PusherSwift', '5.0.0'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '3.2'
      end
    end
  end
end
```

**Comment by karthisiva** [comment]
Thanks a lot, Now working fine. In my live project I have commented below lines in podfile

 post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '3.0'
      end
    end
  end

after that I given **Pod Update**  everything works well.

 sample also working when i have modified pod file  As u said above comment.

I don't know the reason but currently both are working fine.

Thanks for your Time and thanks for reply.

**Pull request merged**
